apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- openhab
- influxdb

namespace: openhab

images:
- name: openhab/openhab
  newTag: 3.2.0-debian
- name: influxdb
  newTag: 2.3.0-alpine
