apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: secrets
  namespace: openhab
spec:
  encryptedData:
    FRITZBOX_IP: AgAywr0FxHG5N5fqWVVyP5lT6qnbVx5vKC4+9ZmOMTZaGiL4EerwNiiH11sD2aDP7fhV0asTfYveru7wJcm8LY7SCECI4proUeIz+cZzhPMPT6P0FpdjuthbunTXY0k/Xvx7wrd0P3/SJW7t81Em97m8bRquUPRj+3nlSlgtDMB3BN4rWKLs+eGXhXr4MuMplO+NaSkfQyBr80X2dnvj/7nCV1kxXgh1Glok9e4yp2ssO/QPsP4it7JdIpg4xyj8lan53cPh4B0igU+qtpHfAvIIsr+QVCJC8izEPok5ckhrPua19OT7xd+gjsY6VkvMqdwFGLcGD0r4okw6+yz7k9mi8oVHnWBnfk1IdtkUMoRqCZgHE7BzJ7qQH6C4PdswtNZFtw7hkxZLTitoYIe5H1i2bL62kT7CTn4sCSBuSVvpahbfeYTdZqi9Ro24Pl5Ifx6MfuwHHUkkAAxhDYMEyBNn2GbBjyUjxfdyOWJJhDuNR8ekgMyWVWx7G43HEA+pRv2X/QbmdpxZ03gGLewplSs+02IM7F07qCF2G2JwK49s6La7NSZQRrUvzgvO6vnSsBDTWS9TOfuyoJs6LOghZHGvIXmMX/V42FiO0Vy9ffgnQVYxxonM76/qgHrIhHfpspbgVEMqsDlJ4JhC2/X7/oUrHEdOk1poI70aKvrLHq5Npx43VgJ7k0OTZjmKIezBRk3TEbOjlxtl8FIjRRQ=
    FRITZBOX_PASSWORD: AgBQzrCtrKDEi+9V3oLP7fkgNuMafc9jX+qxPquXnQ3IC6+WWxVbCnfLSh5vtdG/rntBkxI9VubuYesNkFSGgo+ZYjORVISxziucfJSK+b5SrR9ENrWMFAOhbK//hfAaRRaf/fcItKD5hPkSaRFyzm17m6g0csvywD1tb2IKxotNazv7oni04Je5GvXjcGg3r8xsvKuDmWl7jxwf1ku4Q6z+aX5f8uPl9Yv89SybGHtf0owY2muNCY9tXiYV7cfKfkLg5mgWO5xcHW7HKHU/cFLXTOPH2POvA/tbObxGEsYHhkZiCGROkSCjPxanI1cBUXZnbd69DCTzoTnnbCcK1nEVGChS/THahyMKb6+vkSLXkvMxwcjRp+E3wPjauyr+ZFUnfc+TK4jtmNToAzePGiU3azo1b1Y/vzhyXZdIiJLmWi/IEk6nI3lpqMkjZjSvG1MzIY+CKYuaCS+HOz3zG4pd0bV44iTnXi0rcLUvKKy1o906JbmiTmeHDIcQlTms21HD2vjojS5baMrQg04E8yoG4opHlBIAQ5My5snOl4w4UmKZGJXg/OFsIWo2IvvnMjUzowTTfoqk113HD/FKwiJlMlw7ODEB6qSA6BYk8UfqAr469v5KwERMDyYvDMiUSEOaN/a9ut6CL7Hm+1mzISR2N1ybd2EP5CZcGWZK97Ba8ze6OBY4wuQbc3c8HkxGFsHqlxFlnElNQ3vog3qAnQ1HD0K7mWOH1HcwXX1HwdDmvHCrj9UJOYZc05UvtA==
    FRITZBOX_USER: AgCkH1yFDfoy/vMf3Uw0qoB+1hchJo89hhIWdOMU9PnmuZkNctCyE2BpOxRwNNm8naoq8zQCiyHM8T3J+6bT81QdM9nZferFdQkwrOsFoyVfH0UX9njzGyfa135DnejkVkgmoT+qq8X7shqL7BU6uvEdGE2qrsXAA0Z0t6TXT/URftgG6c81UYoWteEMWJguWQ16ulL2WcJUZ0CQMpSvnZiaXuR5MUMIcKBNN8VXc5xHBIe4e+MfUGvRbAgjaD7OKjkOjhEg6fpX2GTokBiKshHe6dHI2vAB9JAXxTZa0+zVU4dACffmddxLMu54JlxeDhsmgUMKRzB710qItfOJmm0uEJupuLQLBxed3guLjLPFI7biFg5ObxuzXECYyaj2fXlt8dPpS5wb/e5Ljkv1CpUahbVUSFJ2pEWy6u8sOSZlEYljQ5W1xHUByzWlEnPrv/L2ah9rZ/ruNlqFkLD+Vz8iXW3pYc7p33mryqTtWBA3bAqCJOqUryWmR13nC1oRO5k2gIM7pv//dpCdL40bKICqeRei/CORD7jiqOg+Nb1TxW1/WhBy4eUWFe6eC2y/zkhkp4yzj1yKtUQzbaAXaibzztEAsrLP+cTlSFyNvxbus/FFUhoMhwfYdALLmhg1EL0VpmUusF2rAeu7L0dNjB874GFZYDnpOKPStSv4Wqsp7T2iFDL6Px8ZoqX6brIccn+khUUIHfwd
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: secrets
      namespace: openhab

