apiVersion: apps/v1
kind: Deployment
metadata:
  name: analog-gauge-reader
spec:
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - image: captainstandby/analog_gauge_reader
        name: analog-gauge-reader
        command:
        - python3
        - server.py
        - serve
        - /config/gauges.json
        env:
        - name: INTERVAL_SECONDS
          value: '15'
        - name: STREAM_USER
          valueFrom:
            secretKeyRef:
              name: analog-gauge-camera
              key: stream.user
        - name: STREAM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: analog-gauge-camera
              key: stream.password
        - name: STREAM_HOST
          valueFrom:
            secretKeyRef:
              name: analog-gauge-camera
              key: stream.host
        - name: STREAM_URL
          value: rtsp://$(STREAM_USER):$(STREAM_PASSWORD)@$(STREAM_HOST):8554/Streaming/Channels/101
        - name: PYTHONUNBUFFERED
          value: '1'
        ports:
        - containerPort: 8000
          name: metrics
        volumeMounts:
        - mountPath: /config
          name: config
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - all
      volumes:
      - name: config
        configMap:
          name: analog-gauge-config
