apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 16Gi
