apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openhab
spec:
  serviceName: openhab
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 9001
        runAsGroup: 9001
        runAsUser: 9001
      initContainers:
      - image: openhab/openhab
        name: init-directories
        command:
        - /bin/sh
        - -c
        - |-
          rm -f "/openhab/runtime/instances/instance.properties";
          rm -f "/openhab/userdata/tmp/instances/instance.properties";
          [ -z "$(ls -A "/openhab/userdata")" ] && cp -av "/openhab/dist/userdata/." "/openhab/userdata/";
          mkdir -p /openhab/userdata/cache /openhab/userdata/logs /openhab/userdata/persistence /openhab/userdata/tmp
        volumeMounts:
        - name: userdata
          mountPath: /openhab/userdata
        - name: addons
          mountPath: /openhab/addons
      containers:
      - image: openhab/openhab
        name: openhab
        command:
        - /openhab/start.sh
        - server
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
        livenessProbe:
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /
            port: http
        startupProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 20
          timeoutSeconds: 5
          httpGet:
            path: /
            port: http
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: userdata
          mountPath: /openhab/userdata
        - name: addons
          mountPath: /openhab/addons
      volumes:
      - name: userdata
        emptyDir:
          medium: Memory
      - name: addons
        emptyDir:
          medium: Memory
