apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- ingress.yaml
- pvc.yaml

commonLabels:
  app: grafana

configMapGenerator:
- name: grafana-dashboards
  files:
  - dashboards/dashboard.yml
  - dashboards/Heating.json

- name: grafana-datasources
  files:
  - datasources/datasource.yml

- name: grafana-config
  files:
  - grafana.ini
