apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../_common/sealed-secrets
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - sa.yaml
  - tailscale-auth.yaml
  - tailscale-rb.yaml
  - tailscale-role.yaml

commonLabels:
  app: grafana

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/dashboard.yml
      - dashboards/Heating.json

  - name: grafana-datasources
    files:
      - datasources/datasource.yml

  - name: grafana-config
    files:
      - grafana.ini

# generate empty secrets to provide hashed names for deployments
secretGenerator:
  - files:
      - dummy=tailscale-auth.yaml
    name: tailscale-auth
    options:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
    type: Opaque
