apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- pvc.yaml

commonLabels:
  app: prometheus

configMapGenerator:
- files:
  - config.yaml
  name: prometheus-config
