apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: openhab-config-services
  files:
  - services/addons.cfg
  - services/influxdb.cfg.template
  - services/runtime.cfg

- name: openhab-init-scripts
  files:
  - init_config.sh

- name: openhab-config-persistence
  files:
  - persistence/influxdb.persist

- name: openhab-config-things
  files:
  - things/astro.things
  - things/dwdunwetter.things
  - things/ntp.things

- name: openhab-config-items
  files:
  - items/astro.items
  - items/dwdunwetter.items
  - items/ntp.items

- name: openhab-config-transform
  files:
  - transform/astro_de.map
  - transform/de.map
  - transform/dwdunwetter_de.map
  - transform/en.map
