apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- home-assistant

namespace: home-assistant

images:
- name: homeassistant/home-assistant
  newTag: stable
  digest: sha256:f4ce55e5d7dd0a54ba38cf87bb671e78d3bcc93d1a5f5f40bc87aab10eb2fc0b
