apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- analog-gauge-reader
- namespace.yaml

namespace: analog-gauge-reader

images:
- name: captainstandby/analog_gauge_reader
  newName: ghcr.io/captainstandby/analog_gauge_reader:master
