apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - analog-gauge-reader
  - prometheus
  - grafana
  - namespace.yaml

namespace: analog-gauge-reader

images:
  - name: captainstandby/analog_gauge_reader
    newName: ghcr.io/captainstandby/analog_gauge_reader:master
    digest: sha256:d683fa9bbb5cd97abf317fc147c4bf5313feebebb122ce6ed0dbf051f471aeac
  - name: prom/prometheus
    newTag: v2.36.2
  - name: grafana/grafana-oss
    newTag: 9.0.1
  - name: tailscale/tailscale
    newName: ghcr.io/tailscale/tailscale:v1.38.3
    digest: sha256:58e0f0debe050efd6b702ca3f65f33826a5a532dc7236272f37541270caa6a00
