apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- analog-gauge-reader
- prometheus
- namespace.yaml

namespace: analog-gauge-reader

images:
- name: captainstandby/analog_gauge_reader
  newName: ghcr.io/captainstandby/analog_gauge_reader:master
  digest: sha256:d683fa9bbb5cd97abf317fc147c4bf5313feebebb122ce6ed0dbf051f471aeac
- name: prom/prometheus
  newTag: v2.36.2
