{
 "title": "Heating",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LOCATION",
    "label": "Location",
    "query": {
     "query": "analog_gauge{location!=\"None\"}"
    }
   },
   {
    "name": "GAUGE",
    "query": {
     "query": "analog_gauge{location!=\"None\",unit=\"degree Celsius\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Aktuelle Temperatur",
   "type": "gauge",
   "description": "Median der letzten 5m",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (\r\n    quantile_over_time(\r\n        0.5,\r\n        analog_gauge{location=\"$LOCATION\"}[5m]\r\n    )\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "description": "Median der letzten 5m",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (quantile_over_time(0.5, analog_gauge{name=\"Vorlauf\",location=\"$LOCATION\"}[$__interval]) - on(location) quantile_over_time(0.5, analog_gauge{name=\"Ruecklauf\",location=\"$LOCATION\"}[$__interval]))",
     "legendFormat": "Verbrauch"
    }
   ]
  },
  {
   "title": "Vorlauf",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum without (instance) (quantile_over_time(0.5, analog_gauge{location=\"$LOCATION\",name=\"Vorlauf\"}[$__interval]))",
     "legendFormat": "Messung"
    },
    {
     "expr": "sum without (instance) (avg_over_time(analog_gauge{location=\"$LOCATION\",name=\"Vorlauf\"}[6h]))",
     "legendFormat": "Mittel ueber 6h"
    }
   ]
  },
  {
   "title": "Ruecklauf",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum without (instance) (quantile_over_time(0.5, analog_gauge{location=\"$LOCATION\",name=\"Ruecklauf\"}[$__interval]))",
     "legendFormat": "Messung"
    },
    {
     "expr": "sum without (instance) (avg_over_time(analog_gauge{location=\"$LOCATION\",name=\"Ruecklauf\"}[6h]))",
     "legendFormat": "Mittel ueber 6h"
    }
   ]
  }
 ]
}