apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  template:
    spec:
      containers:
      - image: ealen/echo-server:0.5.2
        name: echoserver
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
  - name: http
    port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
spec:
  ingressClassName: nginx
  rules:
  - host: echo.cluster.hlnr.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver
            port:
              name: http
