apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: clusterissuer-secrets
  namespace: cert-manager
spec:
  encryptedData:
    aws.dns01.access_key_secret: AgBahexiYogrF9+j0UtApP4W320H+hl180QDFvKmetMvmL3eHGz6pBdcgQYTVV1fWcjGeWebpc3XuT5naiCq+hSiF5pEIiNlPG2kCo0aZqtd+ITpVDNRVxzbafKNoZKFgOIGbgAER7RtzY+f2VSYe9k2tsznTZcPQGlJJDZIAr7/Ohizhk4qJkh7gzJesv8LRax/xGxShEQUf39PNgn19irNZRuJrWwiA2jSoyWwAbRqexrHPe3g0shdEyIvqllVeh6zgoKAll+mVOIdwhUhuJJbbeno4zgTHrIF/8INqU84uA31WFEYoqh7vvkrogKa/ipXVosAwdMSbnjX271JJrcTtlRM3v6I68FU8U2fKp3RsB6g/0qKS1Z/hotZLcYPxkX1sTV78IUUxfTD8OxgdYVQmvhR42lmlFpZqsPJt88UmosQjL5J+kBgKWYqssNQsIGZwi/pBfKB+icuzGu5abo/DR6wheY2onCCSIQYEokneVwuaTJSOE7PQg89+gY+CKd8aGbxwoMSmZcfsHmQIw2T6P9h/SAQ5uaoWL80XXjkzupSEsyb4M0BvZmsQvRPfWmqWckuqSeaxBQ2I4/X3pfEAJm8S/sjPlPtGGYLJTsX9wQDl0X1/0bl6kcCnzvfMZsIDbz+wPLqCEqoFC2nhQXgUYp5yw6aQKrYGO6uLPV3gAp3d0WFoZuWPvBcFS9VtZHwRtJpF4hS6uspjc18Wct98iDjjNyPeOjXAJ6Qg753j+hRZ8AYaV8v
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: clusterissuer-secrets
      namespace: cert-manager

