apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../_common/sealed-secrets
- clusterissuer.yaml
- clusterissuer-secrets.yaml

# generate empty secrets to provide hashed names for deployments
secretGenerator:
- files:
  - dummy=clusterissuer-secrets.yaml
  name: clusterissuer-secrets
  options:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      sealedsecrets.bitnami.com/managed: "true"
      sealedsecrets.bitnami.com/namespace-wide: "true"
  type: Opaque

namespace: cert-manager

configurations:
- issuer-schema.yaml
