apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openhab
spec:
  template:
    spec:
      initContainers:
      - image: ubuntu
        name: init-conf
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
        env:
        - name: INFLUXDB_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: admin.token
        envFrom:
        - secretKeyRef:
            name: secrets
        command:
        - /bin/sh
        - -c
        - >-
          export DEBIAN_FRONTEND=noninteractive ;
          apt-get update && apt-get -y install --no-install-recommends gettext-base && rm -rf /var/lib/apt/lists/* ;
          /init-scripts/init_config.sh /src-conf /dst-conf ;
          echo "finished initializing config"
        volumeMounts:
        - name: conf
          mountPath: /dst-conf
        - name: init-scripts
          mountPath: /init-scripts
        - name: config-services
          mountPath: /src-conf/services
        - name: config-persistence
          mountPath: /src-conf/persistence
        - name: config-items
          mountPath: /src-conf/items
        - name: config-things
          mountPath: /src-conf/things
        - name: config-transform
          mountPath: /src-conf/transform

      - name: openhab
        volumeMounts:
        - name: etc-localtime
          mountPath: /etc/localtime
        - name: conf
          readOnly: true
          mountPath: /openhab/conf
      volumes:
      - name: conf
        emptyDir: {}
      - name: init-scripts
        configMap:
          name: openhab-init-scripts
          defaultMode: 0555
      - name: config-services
        configMap:
          name: openhab-config-services
      - name: config-persistence
        configMap:
          name: openhab-config-persistence
      - name: config-items
        configMap:
          name: openhab-config-items
      - name: config-things
        configMap:
          name: openhab-config-things
      - name: config-transform
        configMap:
          name: openhab-config-transform
      - name: etc-localtime
        hostPath:
          path: /usr/share/zoneinfo/Europe/Berlin
