apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openhab
spec:
  template:
    spec:
      initContainers:
      - image: openhab/openhab
        name: apply-templates
        env:
        - name: INFLUXDB_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: admin.token
        command:
        - /bin/sh
        - -c
        - |-
          cat /templates/influxdb.cfg.template | sed "s/\${INFLUXDB_ADMIN_TOKEN}/$(printf '%s\n' "$INFLUXDB_ADMIN_TOKEN" | sed -e 's/[\/&]/\\&/g')/" > /openhab/conf/services/influxdb.cfg
        volumeMounts:
        - name: config-templates
          mountPath: /templates
        - name: openhab-conf
          mountPath: /openhab/conf
      volumes:
      - name: config-templates
        configMap:
          name: openhab-config-templates
