apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: openhab

resources:
- base
- ingress.yaml
- volume-claims.yaml

patches:
- add-config.yaml
- add-pvc.yaml

configMapGenerator:
- name: openhab-config-services
  files:
  - config/services/addons.cfg
  - config/services/runtime.cfg
  - config/services/influxdb.cfg

- name: openhab-config-persistence
  files:
  - config/persistence/influxdb.persist

- name: openhab-config-things
  files:
  - config/things/astro.things
  - config/things/dwdunwetter.things
  - config/things/ntp.things

- name: openhab-config-items
  files:
  - config/items/astro.items
  - config/items/dwdunwetter.items
  - config/items/ntp.items

- name: openhab-config-transform
  files:
  - config/transform/astro_de.map
  - config/transform/de.map
  - config/transform/dwdunwetter_de.map
  - config/transform/en.map
