apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: openhab

resources:
- statefulset.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- files:
  - config/services/addons.cfg
  - config/services/runtime.cfg
  name: openhab-config-services
- files:
  - config/persistence/influxdb.persist
  name: openhab-config-persistence
