apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: openhab

resources:
- base
- config
- ingress.yaml
- volume-claims.yaml

patches:
- add-config.yaml
- add-pvc.yaml
- apply-templates.yaml
