apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
spec:
  template:
    spec:
      containers:
      - name: influxdb
        env:
          - name: DOCKER_INFLUXDB_INIT_MODE
            value: setup
          - name: DOCKER_INFLUXDB_INIT_USERNAME
            value: admin
          - name: DOCKER_INFLUXDB_INIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influxdb-secrets
                key: admin.password
          - name: DOCKER_INFLUXDB_INIT_ORG
            value: main
          - name: DOCKER_INFLUXDB_INIT_BUCKET
            value: default
          - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: influxdb-secrets
                key: admin.token
